package main

import (
	"context"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	_ "github.com/lib/pq"
)

const (
	postgresSchemaLockID int64 = 0x4461726c696e6753
	postgresUsersLockID  int64 = 0x4461726c696e6755
)

var errUserLimitReached = errors.New("maximum number of PostgreSQL users reached")

var postgresSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS users (
  user_id UUID PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)`,
	`CREATE TABLE IF NOT EXISTS user_sessions (
  token_hash BYTEA PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ck_user_sessions_token_hash_length CHECK (octet_length(token_hash) = 32)
)`,
	`CREATE TABLE IF NOT EXISTS messages (
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  character_id TEXT NOT NULL,
  sender TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'text',
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, id)
)`,
	`CREATE TABLE IF NOT EXISTS sticker_assets (
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  character_id TEXT NOT NULL,
  emotion TEXT NOT NULL,
  url TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'generated',
  prompt TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at TIMESTAMPTZ,
  PRIMARY KEY (user_id, id)
)`,
	`CREATE TABLE IF NOT EXISTS moments (
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  character_id TEXT NOT NULL,
  author TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, id)
)`,
	`CREATE TABLE IF NOT EXISTS moment_likes (
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  moment_id BIGINT NOT NULL,
  author TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, id),
  CONSTRAINT fk_moment_likes_moment
    FOREIGN KEY (user_id, moment_id)
    REFERENCES moments(user_id, id)
    ON DELETE CASCADE,
  CONSTRAINT uq_moment_likes_user_moment_author
    UNIQUE (user_id, moment_id, author)
)`,
	`CREATE TABLE IF NOT EXISTS moment_comments (
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  moment_id BIGINT NOT NULL,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, id),
  CONSTRAINT fk_moment_comments_moment
    FOREIGN KEY (user_id, moment_id)
    REFERENCES moments(user_id, id)
    ON DELETE CASCADE
)`,
	`CREATE TABLE IF NOT EXISTS moment_checks (
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  moment_id BIGINT NOT NULL,
  author TEXT NOT NULL,
  action TEXT NOT NULL DEFAULT 'seen',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, id),
  CONSTRAINT fk_moment_checks_moment
    FOREIGN KEY (user_id, moment_id)
    REFERENCES moments(user_id, id)
    ON DELETE CASCADE,
  CONSTRAINT uq_moment_checks_user_moment_author
    UNIQUE (user_id, moment_id, author)
)`,
	`CREATE INDEX IF NOT EXISTS idx_user_sessions_user_expiry
  ON user_sessions(user_id, expires_at)`,
	`CREATE INDEX IF NOT EXISTS idx_messages_user_character_id
  ON messages(user_id, character_id, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_sticker_assets_user_lookup
  ON sticker_assets(user_id, character_id, emotion, (COALESCE(last_used_at, created_at)) DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_moments_user_character_id
  ON moments(user_id, character_id, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_moment_likes_user_moment_id
  ON moment_likes(user_id, moment_id, id)`,
	`CREATE INDEX IF NOT EXISTS idx_moment_comments_user_moment_id
  ON moment_comments(user_id, moment_id, id)`,
	`CREATE INDEX IF NOT EXISTS idx_moment_checks_user_moment_id
  ON moment_checks(user_id, moment_id, id)`,
}

func OpenPostgres(ctx context.Context, databaseURL string, maxOpen, maxIdle int) (*sql.DB, error) {
	if ctx == nil {
		return nil, errors.New("open PostgreSQL: context must not be nil")
	}
	databaseURL = strings.TrimSpace(databaseURL)
	if databaseURL == "" {
		return nil, errors.New("open PostgreSQL: database URL must not be empty")
	}
	if maxOpen <= 0 {
		return nil, errors.New("open PostgreSQL: max open connections must be positive")
	}
	if maxIdle < 0 || maxIdle > maxOpen {
		return nil, errors.New("open PostgreSQL: max idle connections must be between zero and max open")
	}

	db, err := sql.Open("postgres", databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open PostgreSQL: %w", err)
	}
	db.SetMaxOpenConns(maxOpen)
	db.SetMaxIdleConns(maxIdle)
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("ping PostgreSQL: %w", err)
	}
	if err := initPostgresSchema(ctx, db); err != nil {
		_ = db.Close()
		return nil, err
	}
	return db, nil
}

func initPostgresSchema(ctx context.Context, db *sql.DB) error {
	if ctx == nil {
		return errors.New("initialize PostgreSQL schema: context must not be nil")
	}
	if db == nil {
		return errors.New("initialize PostgreSQL schema: database must not be nil")
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin PostgreSQL schema transaction: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(ctx, `SELECT pg_advisory_xact_lock($1)`, postgresSchemaLockID); err != nil {
		return fmt.Errorf("lock PostgreSQL schema migration: %w", err)
	}
	for index, statement := range postgresSchemaStatements {
		if _, err := tx.ExecContext(ctx, statement); err != nil {
			return fmt.Errorf("apply PostgreSQL schema statement %d: %w", index+1, err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit PostgreSQL schema: %w", err)
	}
	return nil
}

type PostgresUserStore struct {
	DB       *sql.DB
	MaxUsers int
}

func (s PostgresUserStore) UserExists(ctx context.Context, userID string) (bool, error) {
	if ctx == nil {
		return false, errors.New("check PostgreSQL user: context must not be nil")
	}
	if s.DB == nil {
		return false, errors.New("check PostgreSQL user: database must not be nil")
	}
	normalized, err := normalizePostgresUserUUID(userID)
	if err != nil {
		return false, err
	}
	var exists bool
	if err := s.DB.QueryRowContext(ctx, `SELECT EXISTS (
  SELECT 1 FROM users WHERE user_id = $1::uuid
)`, normalized).Scan(&exists); err != nil {
		return false, fmt.Errorf("check PostgreSQL user: %w", err)
	}
	return exists, nil
}

func (s PostgresUserStore) EnsureUser(ctx context.Context, userID string) (bool, error) {
	if ctx == nil {
		return false, errors.New("ensure PostgreSQL user: context must not be nil")
	}
	if s.DB == nil {
		return false, errors.New("ensure PostgreSQL user: database must not be nil")
	}
	if s.MaxUsers <= 0 {
		return false, errors.New("ensure PostgreSQL user: MaxUsers must be positive")
	}
	normalized, err := normalizePostgresUserUUID(userID)
	if err != nil {
		return false, err
	}
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return false, fmt.Errorf("begin PostgreSQL user transaction: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(ctx, `SELECT pg_advisory_xact_lock($1)`, postgresUsersLockID); err != nil {
		return false, fmt.Errorf("lock PostgreSQL user creation: %w", err)
	}
	var exists bool
	if err := tx.QueryRowContext(ctx, `SELECT EXISTS (
  SELECT 1 FROM users WHERE user_id = $1::uuid
)`, normalized).Scan(&exists); err != nil {
		return false, fmt.Errorf("check existing PostgreSQL user: %w", err)
	}
	if exists {
		if err := tx.Commit(); err != nil {
			return false, fmt.Errorf("commit existing PostgreSQL user: %w", err)
		}
		return false, nil
	}
	var userCount int64
	if err := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM users`).Scan(&userCount); err != nil {
		return false, fmt.Errorf("count PostgreSQL users: %w", err)
	}
	if userCount >= int64(s.MaxUsers) {
		return false, fmt.Errorf("%w: limit=%d", errUserLimitReached, s.MaxUsers)
	}
	result, err := tx.ExecContext(ctx, `INSERT INTO users(user_id)
VALUES ($1::uuid)
ON CONFLICT (user_id) DO NOTHING`, normalized)
	if err != nil {
		return false, fmt.Errorf("insert PostgreSQL user: %w", err)
	}
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, fmt.Errorf("read PostgreSQL user insert result: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return false, fmt.Errorf("commit PostgreSQL user: %w", err)
	}
	return rowsAffected > 0, nil
}

func normalizePostgresUserUUID(value string) (string, error) {
	value = strings.ToLower(strings.TrimSpace(value))
	if len(value) != 32 {
		return "", errors.New("invalid PostgreSQL user id")
	}
	decoded, err := hex.DecodeString(value)
	if err != nil || len(decoded) != 16 {
		return "", errors.New("invalid PostgreSQL user id")
	}
	return value[0:8] + "-" + value[8:12] + "-" + value[12:16] + "-" + value[16:20] + "-" + value[20:32], nil
}
